### ISSUE TITLE
trying to make it run on os x - posix_mime_types.hpp

### ISSUE THREAD

**Issue by dimitre** [morphogencc/ofxAsio#3]
Hello @morphogencc I'm trying to build some pixelpusher example here in OS X.
I've already added and removed the libs folder, but now it complains about

```
#include <boost/date_time/posix_time/posix_time_types.hpp>
```

thanks

**Comment by morphogencc** [comment]
You'll need to change the build settings so it builds without Boost.

Visual Studio uses property sheets (`.props` files) to provide a portable configuration file for build settings.  Does XCode have something similar?

You'll definitely need to define `ASIO_STANDALONE` as a preprocessor definition, and then make sure that you're using a c++11 compiler.  You'll need to set a flag for c++11 features (like `-std=c++11` in gcc) or manually add more preprocessor definitions to force c++11 compatibility.

Visual Studio doesn't have any flag for c++11 settings, so I had to manually specify that my compiler was c++11-compliant.
- `ASIO_HAS_STD_ATOMIC`
- `ASIO_HAS_STD_TYPE_TRAITS`
- `ASIO_STANDALONE`

Good luck!

**Comment by dimitre** [comment]
Thanks for the quick answer and for showing the needed steps!

**Comment by dimitre** [comment]
Great, I was able to advance a bit but got stuck in another error. 

```
/Users/dd/src/of_v0.9.3_osx_release/addons/ofxAsio/src/Datagram.h:89:38: Cast from pointer to smaller type 'unsigned char' loses information
```

Thanks for all the help.

**Comment by morphogencc** [comment]
Hmm, is that the error?  That sounds more like a compiler warning than an error...  I'm not sure what's going on off of the top of my head.

**Comment by morphogencc** [comment]
Particularly, it looks to be this function:

```
    std::vector<unsigned char> getDataAsVector() {
        return std::vector<unsigned char>(reinterpret_cast<unsigned char>(mData.data()), mData.size());
    }
```

Not sure what the proper way to deal with it is; it compiles fine for me, but it might be that I've disabled certain compiler flags.
